# frankenstein — hyprlock config
# arthurr-jpg

background {
    monitor           =
    path              = $HOME/.config/hypr/wallpapers/frankenstein-castle.jpg
    blur_passes       = 3
    blur_size         = 7
    brightness        = 0.45
    contrast          = 1.1
    vibrancy          = 0.25
    vibrancy_darkness = 0.2
}

input-field {
    monitor    =
    size       = 300, 52
    outline_thickness = 2

    # dots — rounding 100 = círculo perfeito
    dot_size     = 0.28
    dot_spacing  = 0.18
    dot_rounding = 100
    hide_input   = true

    outer_color    = rgb(2a4a38)
    inner_color    = rgba(1e2424cc)
    font_color     = rgb(e8e0c8)

    fade_on_empty  = true
    fade_timeout   = 1000

    placeholder_text = <span foreground="##2bc08a" font_family="JetBrainsMono Nerd Font">⚡ password...</span>

    check_color    = rgb(3dd9a0)
    fail_color     = rgb(c0392b)
    fail_text      = <span foreground="##c0392b" font_family="JetBrainsMono Nerd Font"><b>wrong.</b></span>

    # capslock em âmbar, numlock em azul
    capslock_color = rgb(c87820)
    numlock_color  = rgb(60c8f0)
    bothlock_color = rgb(8080f0)

    rounding   = 12
    position   = 0, -90
    halign     = center
    valign     = center
}

label {
    monitor     =
    text        = cmd[update:60000] echo "<span foreground='##3dd9a0'>$(date +'%H:%M')</span>"
    font_family = JetBrainsMono Nerd Font
    font_size   = 72
    color       = rgba(e8e0c8e6)
    position    = 0, 160
    halign      = center
    valign      = center
}

# data
label {
    monitor     =
    text        = cmd[update:60000] echo "$(date +'%A, %d %B %Y')"
    font_family = JetBrainsMono Nerd Font
    font_size   = 15
    color       = rgba(2bc08acc)
    position    = 0, 70
    halign      = center
    valign      = center
}

# branding
label {
    monitor     =
    text        = ⚡ frankenstein · omarchy
    font_family = JetBrainsMono Nerd Font
    font_size   = 11
    color       = rgba(3dd9a060)
    position    = 0, -165
    halign      = center
    valign      = center
}
